<?php echo $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8" />
        <title>stopfraud</title>
        <?php echo $this->headLink()->appendStylesheet('/css/kube.min.css')->appendStylesheet('/css/style.css'); ?>
        <?php echo $this->headScript()->appendFile('/js/jquery-1.8.2.min.js'); ?>
    </head>
    <body>
        <div class="wrapper">
            <div class="row navigation">
                <div class="half centered">
                    <ul>
                        <li><a class="btn" href="/">Home</a></li>
                        <li><a class="btn" href="<?php echo $this->url(array('controller' => 'add', 'action' => 'index'));?>">Add info</a></li>
                    </ul>
                </div>
            </div>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>