<?php echo $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <?php echo $this->headLink()->appendStylesheet('/css/kube.min.css')->appendStylesheet('/css/style.css'); ?>
        <?php echo $this->headScript()->appendFile('/js/jquery-1.8.2.min.js'); ?>
    </head>
    <body>
        <div class="wrapper">
            <div class="navigation">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'add', 'action' => 'index'));?>">Add info</a></li>
                </ul>
            </div>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>